#server.address=127.0.0.1
server:
  port: 9001

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
#      ddl-auto: validate
#  datasource:
#    username: comCpe
#    password: comCpe
#    url: jdbc:mysql://localhost:3306/binome36?useSSL=false
  datasource:
    url: jdbc:h2:mem:user_db
  h2:
    console:
      enabled: true

##### MySQL Database
# docker run --rm -e MYSQL_USER=binome36 -e MYSQL_PASSWORD=binome36 -e MYSQL_DATABASE=binome36 -e MYSQL_ROOT_PASSWORD=toortoor --name=mysql-5.7 -p 3306:3306 mysql:5.7
